import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Kalman Malovicki CV</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='overflow-hidden relative z-20 bg-gray-50'>
        <header className='py-20 md:py-40'>
          <div className='container max-w-6xl flex flex-col items-center gap-26'>
            <Image
              src='/images/kalmi.jpeg'
              alt='Kalmi Malovicki'
              width={640}
              height={750}
              className='max-w-full object-cover rounded-lg'
            />
            <div className='relative bottom-12 left-3 md:left-8 -mb-12'>
              <h1 className='text-5xl md:text-7xl font-bold mb-3 inline-block px-2 rounded pt-4 bg-gray-100'>
                Kalman
                <br />
                Malovicki
              </h1>
            </div>
          </div>
        </header>
        <section className='py-10'>
          <div className='container max-w-3xl grid gap-0 md:gap-14 grid-cols-1 md:grid-cols-2'>
            <h2 className='text-3xl md:text-5xl font-semibold mb-6'>Skills</h2>
            <ul className='text-sm grid grid-cols-1 gap-3'>
              <li>Communicate openly, forcefully and effectively</li>
              <li>Consistently strive to improve performance</li>
              <li>Quickly grasp new routines and explanations</li>
            </ul>
          </div>
        </section>
        <section className='py-10'>
          <div className='container max-w-3xl grid gap-0 md:gap-14 grid-cols-1 md:grid-cols-2'>
            <h2 className='text-3xl md:text-5xl font-semibold mb-6'>
              Experience
            </h2>
            <ul className='text-sm grid grid-cols-1 gap-3'>
              <li>Bnei Akiva Wien: Councelor and Event Manager 2019-dato</li>
              <li>Institute for Talmud Study: Executive Assistant 2019-2021</li>
              <li>Student Government President 2020-2021</li>
              <li>Likrat: Dialogprojekt Wien 2020-dato</li>
            </ul>
          </div>
        </section>
        <section className='py-10'>
          <div className='container max-w-3xl grid gap-0 md:gap-14 grid-cols-1 md:grid-cols-2'>
            <h2 className='text-3xl md:text-5xl font-semibold mb-6'>Awards</h2>
            <ul className='text-sm grid grid-cols-1 gap-3'>
              <li>Rosenfeld Award for Community Engagement</li>
              <li>Merit Scholarships</li>
              <li>ECDL – European Computer Driving License</li>
            </ul>
          </div>
        </section>
        <section className='py-10'>
          <div className='container max-w-3xl grid gap-0 md:gap-14 grid-cols-1 md:grid-cols-2'>
            <h2 className='text-3xl md:text-5xl font-semibold mb-6'>
              Languages
            </h2>
            <ul className='text-sm grid grid-cols-1 gap-3'>
              <li>German - fluent</li>
              <li>English - fluent</li>
              <li>Hebrew - fluent</li>
              <li>French - B2</li>
            </ul>
          </div>
        </section>
      </main>

      <footer className='mt-20 p-2 bg-gray-100 z-10'>
        <div className='container max-w-3xl grid gap-0 md:gap-14 grid-cols-1 md:grid-cols-2  md:rounded py-10'>
          <h2 className='text-3xl md:text-5xl font-semibold mb-6 md:mb-0'>
            Contact
          </h2>
          <div>
            <a
              href='mailto: kalmanmalowicki@gmail.com'
              className='text-lg underline transform hover:text-blue-800'>
              kalmanmalowicki@gmail.com
            </a>
            <p className='text-xs mt-2'>* Request full CV form per email</p>
          </div>
        </div>
      </footer>
    </>
  );
}
